name: Code Summarizer
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get diff from repo
        run: |
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            git diff HEAD~1 HEAD > diff.txt
          else
            git diff $(git hash-object -t tree /dev/null) HEAD > diff.txt
          fi

      - name: Call AI API to summarize diff
        run: |
          diff=$(cat diff.txt)
          current_date=$(TZ="America/New_York" date "+%B %d, %Y")
          payload=$(jq -n --arg diff "$diff" --arg date "$current_date" '{
              "model": "llama-3.3-70b-versatile",
              "messages": [
              {
                "role": "system",
                "content": "Imagine you are developer summarizing what the code does. Whatever you output will be appended to  changelog markdown file. For each entry, I want this exact date to be the title: \($date). Then there should be bullet points that detail the code (different bullets for different block of code/code function). If there is no code then the bullet point should say [No code changed, but a commit was made]."
              }, 
              {
                "role": "user",
                "content": $diff
              }
              ]
            }'  
          )

          curl https://api.groq.com/openai/v1/chat/completions -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GROK_API }}" \
            -d  "$payload" > response.txt

      - name: Modify changelog file
        run: jq -r '.choices[0].message.content' response.txt >> CHANGELOG.md

      - name: Add the author
        run: echo -e '\nChanges by:${{ github.actor }}\n' >> CHANGELOG.md

      - name: Push the changelog file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Updating the changelog"
          file_pattern: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
